# Dependencies
markdown:            kramdown 
highlighter:         pygments

kramdown:
  auto_ids: false

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           "/:title"
relative_permalinks: true

# Setup
title:               Systematic Investor's Blog
tagline:             "Systematic Investor's Blog"
description:         "Systematic Investor's Blog"
url:                 systematicinvestor.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Systematic Investor
  url:               systematicinvestor.github.io
  email:             thesystematicinvestor@gmail.com
     
# Custom vars  
github:
  repo:           github.com/systematicinvestor/systematicinvestor.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       ['About']

exclude:          [rmarkdown, compress]
